### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tyeeman** [hclivess/videer#8]
Just tried to run the exe from the .zip version and get this - 

```
Traceback (most recent call last):
  File "g:\-----N~1\TONYSA~1\videer\videer.py", line 619, in <module>
  File "g:\-----N~1\TONYSA~1\videer\tkinter\__init__.py", line 2071, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined

```
Anything come to mind?

**Comment by hclivess** [comment]
Hello, please try this
https://github.com/hclivess/videer/releases/tag/1.34
